# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csvparser.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63svparser.proto\"&\n\x10\x43SVParserRequest\x12\x12\n\ncolumnName\x18\x01 \x01(\t\"%\n\x11\x43SVParserResponse\x12\x10\n\x08rowCount\x18\x01 \x01(\x03\x32\x41\n\tCSVParser\x12\x34\n\tCountRows\x12\x11.CSVParserRequest\x1a\x12.CSVParserResponse\"\x00\x42+Z)github.com/evgeniyarbatov/grpc-test-driveb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'csvparser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/evgeniyarbatov/grpc-test-drive'
  _globals['_CSVPARSERREQUEST']._serialized_start=19
  _globals['_CSVPARSERREQUEST']._serialized_end=57
  _globals['_CSVPARSERRESPONSE']._serialized_start=59
  _globals['_CSVPARSERRESPONSE']._serialized_end=96
  _globals['_CSVPARSER']._serialized_start=98
  _globals['_CSVPARSER']._serialized_end=163
# @@protoc_insertion_point(module_scope)
